package server.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.paint.Color;

import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.control.TextArea;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.text.Font;
import server.MuzickeZelje;
import server.ServerZahtjevi;

public class DJRajkoController implements Initializable{
	@FXML
	private Font x1;
	@FXML
	private Label lblTrenutnaPjesma;
	@FXML
	private TextArea taLog;
	@FXML
	private ListView lvDrugari;
	@FXML
	private Button btnPrekid;
	@FXML
	private Font x3;
	@FXML
	private Color x4;
	@FXML
	private Label lblIP;
	@FXML
	private Font x31;
	@FXML
	private Color x41;

	// Event Listener on Button[#btnPrekid].onAction
	@FXML
	public void prekid(ActionEvent event) {
		// TODO Autogenerated
	}
	
	/*public static void playNextSong() {
        if (!ServerZahtjevi.muzickeZelje.isEmpty()) {
            String songName = MuzickeZelje.dohvatiPjesmu();
            playSong(songName);
        } else {
            System.out.println("Queue is empty. No more songs to play.");
        }
    }*/
	
	public static void playSong(String songName) {
        // Assume songs are stored in a "songs" directory
        String songPath = "C:\\Users\\libor\\OneDrive\\Documents\\GitHub\\mreze\\mrezni-plejer\\src\\muzicica\\" + songName;

        Media media = new Media(new File(songPath).toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(media);

        mediaPlayer.setOnEndOfMedia(() -> {
            // When the song ends, play the next song in the queue
            //playNextSong();
        });

        // Start playing the song
        mediaPlayer.play();
    }

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
	}
}
