package klijent.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.paint.Color;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.text.Font;

public class UbaciPjesmuController {
	@FXML
	private Font x1;
	@FXML
	private Font x11;
	@FXML
	private ListView<String> lvSvePjesme;
	@FXML
	private Button btnUbaci;
	@FXML
	private Font x3;
	@FXML
	private Color x4;

	// Event Listener on Button[#btnUbaci].onAction
	@FXML
	public void ubaci(ActionEvent event) {
		// TODO Autogenerated
	}
}
